#202504 lqw


bool is_in_enemy_area

bool is_enemy_in_defense_area
float64 hero_x
float64 hero_y
bool is_in_fort_area

bool is_in_tower_area
float64 tower_target_yaw
float64 tower_target_pitch

bool is_in_doghole_area
float64 doghole_target_yaw
float64 doghole_target_pitch

#202507 lqw

bool is_in_dafu_area
float64 dafu_target_yaw
float64 dafu_target_pitch

bool is_in_enemyhalf_area
float64 enemyhalf_target_yaw