std_msgs/Header header
float64 game_type
int16 game_progress
float64 shooter_cooling_rate
float64 shooter_speed_limit
float64 shooter_cooling_limit
float64 robot_id
int16 remain_hp
float64 max_hp
float64 armor_id
float64 hurt_type
float64 bullet_freq
float64 bullet_speed
int16 bullet_remaining_num 
string  key_board
float64 other_robot_id
float64 tgx
float64 tgy
float64 tgz
float64 game_time
int16 enemy_sentry_hp
int16 enemy_outpost_hp
int16 self_outpost_hp
int16 self_base_hp
int16 bullets_num #当前子弹数
#  是否为无敌状态
int8    robot_1
int8    robot_2
int8    robot_3
int8    robot_4
int8    robot_5
int8    robot_7

int8    if_reborn
int8    is_energy_attack_ok

# float64 robot_1_x
# float64 robot_1_y
# std_msgs/Header header
# float64 game_state
# float64 game_time
# float64 remain_hp
