std_msgs/Header header
float64 game_type
float64 game_progress
float64 heat
float64 remain_heat
float64 robot_id
float64 remain_hp
float64 max_hp
float64 bullet_freq
float64 bullet_speed
float64 bullet_remaining_num 
float64 game_time
float64 enemy_outpost_hp
float64 enemy_base_hp
float64 self_outpost_hp
float64 self_base_hp
int16 fort_remain_bullet #当前堡垒弹数
int8    robot_1
int8    robot_2
int8    robot_3
int8    robot_4
int8    robot_5
int8    robot_7
int8    if_reborn
int8    is_energy_attack_ok
int8    posture
int8 can_energy_active
int8 air_outpost #飞手判断 0是不存活点蓝方 1是存活点红方 默认1 
int8 attack_remain_time # 进攻姿态弱化前剩余可持续时长（秒）
int8 defense_remain_time # 防御姿态弱化前剩余可持续时长（秒）
int8 move_remain_time # 移动姿态弱化前剩余可持续时长（秒）
int8 enhanced_attack_remain_time # 强化进攻姿态剩余可持续时长（秒）
int8 enhanced_defense_remain_time # 强化防御姿态剩余可持续时长（秒）
int8 enhanced_move_remain_time # 强化移动姿态剩余可持续时长（秒）
